name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  MONGO_URI: ${{ secrets.MONGO_URI }}
  TEST_MONGO_URI: ${{ secrets.TEST_MONGO_URI }}
  TEST: True

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install backend dependencies
        run: pip install -r ./requirements.txt
      - name: Run pylint
        run: pylint src --rcfile=.pylintrc
      - name: run pytest
        run: coverage run --branch -m pytest -m "not api"
      - name: Coverage report
        run: coverage xml
      - name: Coverage report to Codecov
        run: bash <(curl -s https://codecov.io/bash)
      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        if: ${{ github.event_name == 'push' }}
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
